### ISSUE TITLE
Route availability and feature status at `/v4/status`

### ISSUE THREAD

**Issue by oponder** [giantswarm/api-spec#14]
As a user, I want to find out whether I can currently create a new cluster. The system responds with either a positive answer or, in case of a negative one, with details about the reason.

Marian came up with the nice idea of using the Route and Method itself to describe the feature like so:

```
GET /v4/status/
{
  "/v4/clusters/": {
    "POST": {
      "available": false,
      "reason": "Scheduled maintenance. Creating clusters won't be possible.",
      "start": "2017-05-24T22:00:00Z",
      "end": "2017-05-25T00:00:00Z",
    }
  }
}
```

I'd like to discuss where this data will be stored, and also how we can manipulate it as admins.

I think we'll need a new admin only routes: PATCH /v4/status, for us to be able to make changes to the availability.

**Comment by oponder** [comment]
I still think this is a cool idea :) Adding it to SIG UX so it can maybe end up getting prioritised some day when we have the time.

**Comment by marians** [comment]
Discussed briefly in SIG UX sync. As this goes deep into our processes, but doesn't have a customer request or any product priority, we'll close it. Also related to the deprecated API.
