### ISSUE TITLE
Discuss: Adding a `ATTRIBUTE_IMMUTABLE` response code

### ISSUE THREAD

**Issue by oponder** [giantswarm/api-spec#17]
Currently for input validation we have `UNKNOWN_ATTRIBUTE` as a possible error response. It is used to indicate that the request contains unexpected fields.

However in some cases the attribute that is part of the request is known, but simply not allowed to be edited.

Consider from the point of view of a user, the following response to attempting to patch a cluster:

```
REQUEST PATCH /v4/clusters/:clusterid/
{
"name": "Changed name"
}
```

```
RESPONSE 400
{
"code": "UNKNOWN_ATTRIBUTE",
"message": "unknown attribute `name`"
}
```

This is what the user would see right now in the current state of the API.

The user might think that `name` is spelled wrong. He might go to try `clusterName` instead or something like that instead.

Instead it would be better if he got back: 

```
RESPONSE 400
{
"code": "ATTRIBUTE_IMMUTABLE",
"message": "attribute `name` is immutable. You are not allowed to change it."
}
```

That way there is no confusion for the user. 

Motivated by the discussion here: https://github.com/giantswarm/api/issues/324 where we were mostly in agreement on adding something like this.

Just wanted to start the discussion to see if we need to refine it any further.

Thoughts @marians @xh3b4sd ?

**Comment by xh3b4sd** [comment]
I like that. Makes sense to me. Go for it.

**Comment by oponder** [comment]
Related to: https://github.com/giantswarm/api-spec/issues/17

**Comment by oponder** [comment]
Discussion complete. I'll try to make the needed changes to `api` and `microkit`

**Comment by oponder** [comment]
Hey guys, we agreed on calling it `ATTRIBUTE_IMMUTABLE` but `IMMUTABLE_ATTRIBUTE` is more in line with the way we named our other attribute related error: `UNKNOWN_ATTRIBUTE`

Is it ok to make the error code `IMMUTABLE_ATTRIBUTE` for consistency?

**Comment by marians** [comment]
Fine with me
