### ISSUE TITLE
Support Scaling in API

### ISSUE THREAD

**Issue by oponder** [giantswarm/api-spec#24]
We need to discuss how scaling of worker nodes should work.

Related to: https://github.com/giantswarm/giantswarm/issues/1270

@puja @rossf7  @marians @oponder

**Comment by marians** [comment]
- Scaling up and down should be done using simple patch requests.
  - We are aware of possible concurrency problems. This might be solved at a future point, e. g. using revision IDs.
- Auto scaling groups might take care of keeping the required amount of healthy nodes up. This isn't exposed via the API.
- By giving nodes unique labels, users can enforce removal of a specific node when required
- At first, removing a node will not drain the worker. Users will have to take care themselves. Our UIs should give appropriate warning.
- We need to restrict AWS clusters to using the same instance type for all nodes (as an intermediate step). We should have simple validation, throwing an issue when this restriction isn't met.

**Comment by marians** [comment]
FYI: I removed the word "Update" from the title, as this here is about scaling only. "Updating" implies a change of the k8s version.

**Comment by puja108** [comment]
btw, we should maybe also have a look at https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md to see if we could be compatible with the standard autoscaler somehow or at least not break certain standards

**Comment by marians** [comment]
Implementation is tracked in https://github.com/giantswarm/api/issues/405. Closing this.
