### ISSUE TITLE
Question: How to approach add / remove members from organizations

### ISSUE THREAD

**Issue by oponder** [giantswarm/api-spec#29]
@marians how do you think we should approach adding and removing members from organizations?

Do you think we should use `PATCH /v4/organizations/:org-id/` with some json in the body representing the full final state of the members as the user wants it to be?

```
              {
                "members": [
                  {"email": "user1@example.com"},
                  {"email": "user2@example.com"},
                  {"email": "user3@example.com"},
                ]
              }
```

Meaning that user then has to supply the full list of members each time he wants to add one. (And the full list of members, minus the one he wants to remove, each time he wants to remove one.) But a benefit is that bulk operations are now possible.

Or do we go for something like:

`PUT /v4/organizations/:org-id/members/:email/`
`DELETE /v4/organizations/:org-id/members/:email/`

Meaning we leak personally identifiable information in our requests over the wire.

**Comment by oponder** [comment]
Oh nevermind, I am apparently mistaken about the leaking information bit. URLs are encrypted too as part of https

**Comment by marians** [comment]
I think we should use PATCH for all resource updating, so also in this case here. When `members` is the only attribute of the resource, then the PATCH payload will in fact represent the entire resource.

**Comment by oponder** [comment]
> I think we should use PATCH for all resource updating

Agreed. But we could add the "/v4/organizations/:org-id/members/" resource, and then standard  `PUT` / `DELETE` becomes possible.

We're not forced to support PATCH for every field on every resource. We can make `members` an immutable field on the `organizations` resource if we want to. And introduce `members` as a resource.

That would be a lot simpler to implement right now, and means people wouldn't have to send a large list members each time they want to add or remove one. We'd also have to implement `revision id` to avoid concurrency issues. 

(i.e. someone else might add a member in between the time that the you fetched the list of all members, changed it, and then `PATCH`ed it back. Or basically the same situation we're going to face with the cluster scaling)

**Comment by oponder** [comment]
Anyways I'm fine with implementing `PATCH` on the organizations resource. I just thought from a ux point of view its a bit nicer to have a members resource that we can `PUT` / `DELETE`

But then I realised if people are using happa or gsctl, then it doesn't matter too much. Though it is easier to automate, if some service down the line wants to add / remove a member from an organization, it effectively becomes a two request process (fetch the org, edit the list, patch the org)

Any final thoughts? I would still prefer having a `members` resource, but if you're against that, I can go with the `PATCH` on the organizations resource.

**Comment by oponder** [comment]
Chatted with Marian about this. Decision is to go with `PATCH` on organizations resource. `api-spec` pr incoming (layer today or tmw morning)
